### ISSUE TITLE
Segfault error

### ISSUE THREAD

**Issue by jmp-1902** [aklomp/shrinkpdf#16]
Experiencing Segmentation Fault (core dumped) error for some PDFs. How to solve?

**Comment by aklomp** [comment]
There's not a lot of detail in this bug report. What's crashing, exactly? What are the symptoms? Can we reproduce it?

My guess is that the crash is happening in Ghostscript, because that's where most of the complexity is. If that's the case, you'll want to file the bug with the Ghostscript project. This project is just a thin wrapper script around other tools.
