### ISSUE TITLE
When input file is same as output the result is an empty pdf file

### ISSUE THREAD

**Issue by whygee-dev** [aklomp/shrinkpdf#3]
Adding support for such case would be useful, otherwise handling manually a temporary file is needed

**Comment by aklomp** [comment]
My first reaction is: that's usually how it works in the terminal. If you use an input file as an output, your data will be truncated.

But I agree that this script can do slightly better, and can detect some situations where it would truncate the input file, and refuse to continue.

The first issue that we need to detect when the input and output file are the same. The most robust yet simple way I could find is `if [ "$1" -ef "$2" ]`, but unfortunately `shellcheck` rejects the `-ef` operator because it is not in [POSIX `test`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html).

The next best option is to test for string equality. That should catch the majority of truncation cases. I pushed a [branch](https://github.com/aklomp/shrinkpdf/tree/issue3) that should work.

As for autogenerating a temporary file and using that instead, I'd rather not go there. It would complicate the script and it would be hard to make it portable.

**Comment by aklomp** [comment]
@whygee-dev does the `issue3` branch that I pushed solve this issue for you?
